global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
        
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090

- job_name: node
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: wallet
  static_configs:
  - targets:
    - eth-exporter:9015
